services:
  recipes-api:
    image: italomdd/spring-recipes-api
    build: .
    ports:
      - "8080:8080"
    networks:
      - recipes-api-network
    environment:
      - API_DATASOURCE_URL=recipes-api-db
      - API_DATASOURCE_USERNAME=root
      - API_DATASOURCE_PASSWORD=12345
    depends_on:
      recipes-api-db:
        condition: service_healthy
    volumes:
      - api-data:/api
  recipes-api-db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - recipes-api-network
    ports:
      - "3306:3306"
    volumes:
      - api-data:/db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10
networks:
  recipes-api-network:
volumes:
  api-data: