spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/recipes_db
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  error:
    include-stacktrace: never
api:
  security:
    jwt:
      secret: ${JWT_SECRET:123456789}
      issuer: recipes_api
springdoc:
  swagger-ui:
    path: /api/docs/ui
  api-docs:
    path: /api/docs